apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-ids-data-pvc
  labels:
    app: network-ids
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
